### PR TITLE
added KOWABUNGA

### PR DESCRIPTION
**Pull request by trial646**
phase 2 completed

### CODE REVIEW

**Comment by trial646** [comment]
Did this work Tyler?

**Comment by trial646** [comment]
That was addressed to Tyler: Bontgoy

**Comment by trial646** [comment]
@bontgoy I was missing the @ symbol. Did it work this time?

**Comment by Bontgoy** [comment]
@trial646 This looks good!  Thanks for sending it over.  :shipit:

**Comment by trial646** [comment]
@Bontgoy tagging again for this pm request

**Pull request merged**
